config/routes.rb
Rails.application.routes.draw do
  root 'requests#index'
  resources :schedule 
  resources :requests do
    member do
      patch :close_out, :reopen
    end
    resources :samples do
      collection { post :import }
      member do
        patch :complete , :set_as_empty, :remove_complete, :remove_empty
      end
    end
  end
end

app/models/sample.rb
class Sample < ApplicationRecord
    belongs_to :request, optional: true

    amoeba do
        enable
        nullify [:is_empty, :time_completed, :complete]
      end

    def completed?
        !time_completed.blank?
    end

    def empty?
        !is_empty.blank?
    end

    def self.import(file, request, size="250mL")
        return if file.blank?
         spreadsheet = Roo::Spreadsheet.open(file.path)
         sizer = spreadsheet.cell(2,3)
         size = sizer if !sizer.blank?
        # spreadsheet.set_value(1,3, 'request_id', nil)
        # header = spreadsheet.row(1)
        # header.push('request_id')
        header = ['tank','lot_id','request_id']
         (2..spreadsheet.last_row).each do |i|
           spreadsheet.set_value(i, 3, request.id, nil)
           row = Hash[[header, spreadsheet.row(i)].transpose]
           puts row
           puts "hello joe!"
           
           sample = Sample.new
           puts sample.sample_size 
           puts "hi"
           sample.attributes = row
           sample.sample_size = size if  sample.sample_size.blank?
           sample.save!
         end
       end 
=begin
    def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then CSV.new(file.path, nil, :ignore)
        when ".xls" then Excel.new(file.path, nil, :ignore)
        when ".xlsx" then Excelx.new(file.path, nil, :ignore)
        else raise "Unknown file type: #{file.original_filename}"
        end
    end
=end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
    before_action :set_request, except: [:index]
    before_action :set_sample, except: [:create, :import, :index]


    def index
      @samples = Sample.all
      @complete_samples = @samples.select{|h| h.time_completed}
      @incomplete_samples = @samples.select{|h| !h.time_completed}
    end

    def create
      @sample = @request.samples.create(sample_params)
      redirect_to "#{url_for(@request)}##{@sample.id}"
    end
  
    def destroy
      if @sample.destroy
        flash[:success] = "Sample was deleted"
      else
        flash[:error] = "Sample could not be deleted."
      end
      redirect_to "#{url_for(@request)}##{@sample.id-1}"
    end

    def edit
        @sample
    end

    def update
        @sample.update sample_params
        redirect_to "#{url_for(@request)}##{@sample.id}", notice: "Sample Updated!"
    end
  
    def complete
      @sample.update_attribute(:time_completed, Time.now.in_time_zone)
      redirect_to "#{url_for(@request)}##{@sample.id}", notice: "Sample Completed!"
    end

    def remove_complete
      @sample.update_attribute(:time_completed, nil)
      redirect_to "#{url_for(@request)}##{@sample.id}", notice: "Sample Not Complete"
    end

    def import
      if params[:file].blank?
        flash[:error] = 'No file selected.'
      end
      Sample.import(params[:file], @request, params[:sample_size])
      redirect_to @request, notice: "Samples imported"
    end

    def set_as_empty
      @sample.update_attribute(:is_empty, true)
      redirect_to "#{url_for(@request)}##{@sample.id}", notice: "Tank Empty!"
    end

    def remove_empty
      @sample.update_attribute(:is_empty, nil)
      redirect_to "#{url_for(@request)}##{@sample.id}", notice: "Tank Not Empty!"
    end
  
    private
  
    def set_request
      @request = Request.find(params[:request_id])
    end
  
    def set_sample
      @sample = @request.samples.find(params[:id])
    end
  
    def sample_params
      params[:sample].permit(:tank, :lot_id, :sample_size)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_close.html.erb
<div class="closed-request-header" id="closed-header">
    <h5 class="closed-details" style="color: white; "><strong>Request ID: </strong><%=@request.id%></h5>
      <h5 class="closed-details" style="color: white;"><strong>Created:  </strong><%=@request.created_at.strftime("%A,  %B %d @ %H:%M:%S")%></h5>
    <h5 class="closed-details" style="color: white;"><strong>Request Closed:  </strong><%=@request.time_completed.strftime("%A,  %B %d @ %H:%M:%S") %></h5>
    <h6 class="closed-header"  style="color: white;"><strong># Samples:  </strong><%= @request.samples.count %></h6>
</div>
<div class="uk-background-muted">
<table class="uk-table uk-table-divider" >
    <tr>
        <th>Sample ID  </th><th>Tank   </th><th>Lot   </th><th>Sample Size </th><th>Time Completed</th>
    </tr>
         <% @request.samples.each do |sample|%>
    <tr class="sample-row">
        <td><%=sample.id%></td><td><%=sample.tank%>    </td><td> <%=sample.lot_id%>    </td><td><%=sample.sample_size%></td>
            <%if sample.empty?%>
                <td>TANK EMPTY</td>
            <%elsif sample.completed?%>
                <td><%=sample.time_completed.strftime("%A,  %B %d @ %H:%M:%S")%></td>
             <%end%>
    </tr>
        <%end%>
</table>
</div>

app/views/samples/_form.html.erb
<% if @request.time_completed == nil%>
  <form class="new_sample" id="new_sample" action="/requests/<%=@request.id%>/samples" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="EqWOFSvl+TibILmopmoMAxXSa/xhseyu8Q0bF2S70J5ctflv//3jBOmAHfWcfFzw7ZrCtqTeTua1fToW5PbdnQ==">
    <input placeholder="New Tank" class="uk-input" type="text" name="sample[tank]" id="sample_tank">
    <input placeholder="Lot ID" class="uk-input" type="text" name="sample[lot_id]" id="sample_lot_id"><br>
    <span class="form"><select class="uk-form-width-small" name="sample[sample_size]" id="sample_sample_size"><option value="250mL">250mL</option>
  <option value="375mL">375mL</option>
  <option value="750mL">750mL</option></select>
    <input type="submit" name="commit" value="Add Sample" data-disable-with="Add Sample">
  </span></form><br>

  <div class="uk-form-stacked">
  <span><%= form_tag import_request_samples_path(@request, params[:sample_size]), multipart: true do |f| %>
    
    <div class="uk-margin" uk-margin>
    <img src="https://png.icons8.com/color/64/000000/xls.png">
          <div uk-form-custom="target: true">
              <input type="file" id="file" name="file" uk-tooltip="title: Select CSV File to Import">
              <input class="uk-input uk-form-width-medium"  type="text" placeholder="Select file" disabled>
          </div>
        
  <span class ="import" uk-tooltip="title: Import Samples from CSV File"><%= submit_tag "Import" %>--<%= select_tag( :sample_size, options_for_select(['250mL','375mL','750mL']))%>
    </div>
  <% end %></span></span>

  </div>
<%end%>

app/views/samples/_sample.html.erb
<div class="row clearfix">
	
	<% if sample.empty? %>
		<div class="complete">
			
				<img src="https://png.icons8.com/windows/30/000000/hibernate.png">
			<br><br>
			<%=sample.sample_size%>
			
		</div>
		
		<div class = "empty" id=<%=sample.id%>>
			<p>TANK <%= sample.tank%> IS EMPTY</p>
		</div>
		<div class="right-block">
			<div class="set-empty">
				<%= link_to remove_empty_request_sample_path(@request, sample.id), method: :patch do %>
					<span uk-tooltip="title: Undo Empty" ><%=image_tag("minus-sign-32.png")%></span>
				<% end %>
			</div>
			<div class="trash"  uk-tooltip="title: Delete Sample">
				<%= link_to request_sample_path(@request, sample.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<span uk-tooltip="title: Delete Sample"><%=image_tag("trash-64.png")%></span>
				<% end %>
			</div>
		</div>
	<%end%>
	<% if sample.completed? %>
		<div class="complete">
			<%= link_to remove_complete_request_sample_path(@request, sample.id), method: :patch do %>
				<span  uk-tooltip="title: Undo Complete"><%=image_tag("Doc_Ex-64.png")%></span>
	        	<% end %><br><br>
			<%=sample.sample_size%>
		</div>
		<div class="completed" id=<%=sample.id%>>
			<p style="opacity: 0.4;">
				<strike><%= sample.tank %></strike>|
				   <strike><%= sample.lot_id %></strike>
				 <span uk-icon="icon: check; ratio: 2"></span>
				<img src="https://png.icons8.com/nolan/30/000000/checkmark.png">
			</p>
			<li<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHMSURBVGhD7djBK2VhHMbxy8gChYXQxEiJlL3EanajWcnaWIyFYikLyj+glBRZKWUpstXU2EhZMIvZKwuLaULNIOL7nJw63Xvf2733LN738nvqU973uPo9nXPuPVfG8g4yi2s8O5yhF0GnGY/IVyBpB0FnABr0PFrlZhg6fhStAk5c5Fe0ys0IKqJIHe6gYbe0kUg7/kLHNrURer5Dw2ZfXvFldYk2bYQe131SMfdHHCsSWqxIaLEiIUUfetvQwHo4TGYI2teH4jdUIchM4hYa9gHzSKYBJ9Bx+YmPCCoaOh5wH5+QLzoL47iCfvcC3QgiY9BQenyf0kYRacEP6HW/UQ+vacQfaKBpbZQQPWCeQq9d1obPzEGDHEar0tOPJ/yDzpK3HENFvkSr8nIA/Y2JaOUh1dB9IU3oRB86UItiMwMVWY9WHtIKDaBL4/7155jWOlt6N1PBQvkKvWY3WnmIBkwO76IztodRfEB24k98XWJeUmyRJH07XIXepj9jEAvQsYoqUogVSRsr4mBF0saKOFiRtLEiDlYkbayIgxVJGyviYEXSxoo4eCtSg//IN1Q51uAti8g3VKlu0AOv0f+lVrBRpiV0wfKGksm8AMpJOO37/krXAAAAAElFTkSuQmCC">
			<%=sample.sample_size%> Sample of tank <%= sample.tank %> collected:<br> <%= sample.time_completed.strftime("%A,  %B %d @ %H:%M:%S")%></li>
		</div>
		<div class="right-block">
			<div class="set-empty">
				
					<img src="https://png.icons8.com/nolan/30/000000/high-priority.png">
				
			</div>
			<div class="trash">
				<%= link_to request_sample_path(@request, sample.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<span uk-tooltip="title: Delete Sample"><%=image_tag("trash-64.png")%></span>
						<% end %>
			</div>
		</div>
	<% elsif !sample.empty? %>
		<div class="complete">
			<span  uk-tooltip="title: Mark Sample Complete"><%= link_to complete_request_sample_path(@request, sample.id), method: :patch do %>
				
				<%=image_tag('blueCheck-64.png')%></span>
	        	<% end %><br><br>
				
			<%=sample.sample_size%>
		</div>
		<div class="sample" id=<%=sample.id%>>
			<p><%= sample.tank %></p>
			<%= sample.lot_id %>  
		</div>
		<div class="right-block">
			<div class="set-empty">
				<%= link_to set_as_empty_request_sample_path(@request, sample.id),  method: :patch do %>
					<span  uk-tooltip="title: Mark Tank Empty"><%= image_tag("empty.png")%></span>
				<% end %>
			</div>
			<div class="trash">
				<%= link_to request_sample_path(@request, sample.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<span uk-tooltip="title: Delete Sample"><%=image_tag("trash-64.png")%></span>
					<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/samples/edit.html.erb
<%= form_for([@request, @request.samples.build]) do |f| %>
  <%= f.text_field :tank,  placeholder: "New Tank" %>
  <%= f.text_field :lot_id,  placeholder: "Lot ID" %>
  <%= f.select :sample_size, ['250mL', '375mL','750mL'] %>
  <%= f.submit "Add Sample" %><br>
<% end %><br>