config/routes.rb
Rails.application.routes.draw do
  root 'requests#index'
  resources :schedule 
  resources :requests do
    member do
      patch :close_out, :reopen
    end
    resources :samples do
      collection { post :import }
      member do
        patch :complete , :set_as_empty, :remove_complete, :remove_empty
      end
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
    has_many :samples

    amoeba do
        enable
        nullify [:time_completed, :complete]
        clone :samples
      end

    def completed?
        !time_completed.blank?
    end
    
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    before_action :set_request, only: [:show, :edit, :update, :destroy, :close_out, :reopen]
    def index
        @requests = Request.all
        @requests.reverse
        @complete_requests = Request.where(complete: true)
        @complete_requests.sort{|x,y| y.time_completed - x.time_completed}
        @incomplete_requests = Request.where(time_completed: nil)
        @incomplete_requests.reverse

    end

    def show
        @request = Request.find(params[:id])
    end

    def new
        @request = Request.new
    end

    def create
        @request = Request.create request_params
        @request.complete = false
        redirect_to request_path(@request)
    end

    def edit
        @request = Request.find(params[:id])
    end

    def update
        @request = Request.find(params[:id])
        @request.update request_params
        redirect_to request_path(@request)
    end

    def destroy
        Request.find(params[:id]).destroy
        redirect_to root_path
    end

    def import
        Sample.import(params[:file])
       # redirect_to @request, notice: "Samples imported"
    end

    def close_out
        @request.update_attribute(:time_completed,  Time.now.in_time_zone)
        @request.update_attribute(:complete,  true)
        if @request.is_recurring
            new_request = @request.amoeba_dup
            new_request.due_date = @request.due_date + @request.recurrence_interval.days
            new_request.save!
        end
        redirect_to @request, notice: "Request Completed!"
    end

    def reopen
        @request.update_attribute(:time_completed, nil)
        @request.update_attribute(:complete, false)
        redirect_to @request, notice: "Request Re-opened!"
    end
        
        
  
    private
        def set_request
            @request = Request.find(params[:id])
        end

        def request_params
            params.require(:request).permit(:title, :description, :due_date, :is_recurring, :recurrence_interval)
        end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_complete.html.erb
<div class="hidden">
  <% @complete_requests.reverse.each do |request| %>
    <div class="completed-request">
      <div class="index_row clearfix">
          <h2 class="request_title"><strike><%= link_to request.title, request %></strike><%=image_tag('blueCheck-64.png')%></h2>
        <p class="request_sub_title"><strike><%= request.description %></strike><br>
              Due: <%= request.due_date.strftime("%A, %B %d")%><br>
              Completed: <%= request.time_completed.strftime("%A,  %B %d @ %H:%M:%S")%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div><br>

   <div class="field">
   <label uk-tooltip="Date this request is expected to be completed">Due Date</label>
    <%= f.date_select :due_date %>
  </div><br>

    <div class="field" id="recurring" >
      <label uk-tooltip="title: If set to true a new request will be generated with the same title, description, and samples with a due date one interval length after current due date after current request closes"> 
        Is Recurring?
      </label>
    <%= f.select :is_recurring, [true,false], :selected => false %>
  
  </div><br>
    <div class="field" id="interval" style="display:none">
    <%= f.label :recurrence_interval %>
    <%= f.select :recurrence_interval, [1,2,3,4,5,6,7] %><label> day(s)</label>
  </div><br>
  <div class="actions" id="new-request">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/_incomplete.html.erb
<div class="hidden">
  <% @incomplete_requests.reverse.each do |request| %>
    <div class="incomplete-request">
      <div class="index_row clearfix">
        <h2 class="request_title"><%= link_to request.title, request %></h2>
        <p class="request_sub_title"><%= request.description %><br>
                <%= request.due_date.strftime("%A, %B %d") %></p> 
      </div>
    </div>
  <% end %>
</div>

app/views/requests/_list.html.erb
<% @requests.each do |request| %>
  
    <div id="completed" class="index_row clearfix">
      <%if request.completed?%>
        <h2 class="request_title"><strike><%= link_to request.title, request %></strike></h2>
      <p class="request_sub_title"><strike><%= request.description %></strike><br>
                    Due: <%= request.due_date.strftime("%A, %B %d")%><br>
            Completed: <%= request.time_completed.strftime("%A, %B %d")%></p>
      <%else%>
      <h2 class="request_title"><%= link_to request.title, request %></h2>
      <p class="request_sub_title"><%= request.description %><br>
              <%= request.due_date.strftime("%A, %B %d")%></p>
  
    <%end%>
    </div>
<% end %>

app/views/requests/edit.html.erb
<h1 class="request_title">Edit Request</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', requests_path %>
</div>

app/views/requests/index.html.erb
<div class="filter-bar">

  <p><label>Show Completed</label><input type="checkbox" class="uk-checkbox" name="show-complete" id="show-complete" value="show-complete" checked="yes">  ||
  <label>Show Incomplete</label><input type="checkbox" class="uk-checkbox" name="show-incomplete" id="show-incomplete" value="show-incomplete" checked="yes"></p>
</div>

<div id="incomplete-list" class="hidden">
  <div class="request-label">Incomplete Requests</div>
    <%= render(partial: 'requests/incomplete') %>
</div>
<div id="complete-list" class="hidden">
  <div class="request-label">Completed Requests</div>
    <%= render(partial: 'requests/complete') %>
</div>

<div class="links">
 <%=image_tag("doc-add-64.png")%> <%= link_to "New Request", new_request_path %>
</div>

app/views/requests/new.html.erb
<h1 class="request_title">New Request</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', requests_path %>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="request_title"><%= @request.title %></h2>
<p class="sub"><%= @request.description %><br><br>
 Due Date: <%= @request.due_date.strftime("%A, %B %d") %><br>
 <%if @request.is_recurring%>
 Recurring: <%=@request.is_recurring %><br>
 Interval: <%=@request.recurrence_interval%> days
<%end%><br>

 	<% if !@request.time_completed %>
	
	 <span uk-icon="file-edit" uk-tooltip="title: Edit Request Details" ><%= link_to edit_request_path(@request) do  %>
	 <br>
	 <%=image_tag("edit.png")%>
	 </span>
	
	<%end%>
	

<div class="closed-link" >
<%= link_to close_out_request_path(@request), method: :patch do %>
	<span uk-tooltip="title: Close-Out Request"><%=image_tag("complete-64.png") %><br>Close Out</span>
	<% end %>
</div>
<%else%>
<div class="closed-link"uk-tooltip="title: Re-Open Request" >
	<%= link_to reopen_request_path(@request), method: :patch do %>
		<%=image_tag("Write_64.png") %><br>Re-Open
	<% end %></p>
</div>
<%end%></p>



<div id="samples_wrapper">

	<%if @request.time_completed%>
	
		<%= render "samples/close"%>
	
	<%else%>
	<p class="uk-text-primary"><%= @request.samples.count %> samples</p>
		<% samples = @request.samples.sort_by{|h| h.tank.to_i} %>
		
		<%= render samples  %>
		
	
	<%end%>
		
	<div id="form">
		<%= render "samples/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_request_path(@request) %> |
	<%= link_to 'Delete', request_path(@request), method: :delete, data: { confirm: "Are you sure?" }%> |
    <%= link_to 'Back', requests_path %> |
	<a href="/schedule?start_date=<%=Time.zone.now.strftime("%Y-%m-%d")%>">Schedule</a>
</div>